services:

  vault-server:
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: ${DEVEL_ROOT_TOKEN}

  vault-client:
    environment:
      VAULT_TOKEN: ${DEVEL_ROOT_TOKEN}
